2025-02-09 08:25:21,574 ERROR The joined path (C:\Users\ivano\simple-votings-py-charmers\main\media\avatars\default.png) is located outside of the base path component (C:\Users\Мирослав\votings\simple-votings-py-charmers\simple-votings-py-charmers\main\media)
Traceback (most recent call last):
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\ivano\simple-votings-py-charmers\main\media\avatars\default.png) is located outside of the base path component (C:\Users\Мирослав\votings\simple-votings-py-charmers\simple-votings-py-charmers\main\media)
2025-02-09 08:25:21,631 WARNING Bad Request: /media/C:/Users/ivano/simple-votings-py-charmers/main/media/avatars/default.png
2025-02-09 08:25:55,059 ERROR The joined path (C:\Users\ivano\simple-votings-py-charmers\main\media\avatars\default.png) is located outside of the base path component (C:\Users\Мирослав\votings\simple-votings-py-charmers\simple-votings-py-charmers\main\media)
Traceback (most recent call last):
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\ivano\simple-votings-py-charmers\main\media\avatars\default.png) is located outside of the base path component (C:\Users\Мирослав\votings\simple-votings-py-charmers\simple-votings-py-charmers\main\media)
2025-02-09 08:25:55,075 WARNING Bad Request: /media/C:/Users/ivano/simple-votings-py-charmers/main/media/avatars/default.png
2025-02-09 08:25:57,059 ERROR The joined path (C:\Users\ivano\simple-votings-py-charmers\main\media\avatars\default.png) is located outside of the base path component (C:\Users\Мирослав\votings\simple-votings-py-charmers\simple-votings-py-charmers\main\media)
Traceback (most recent call last):
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\ivano\simple-votings-py-charmers\main\media\avatars\default.png) is located outside of the base path component (C:\Users\Мирослав\votings\simple-votings-py-charmers\simple-votings-py-charmers\main\media)
2025-02-09 08:25:57,079 WARNING Bad Request: /media/C:/Users/ivano/simple-votings-py-charmers/main/media/avatars/default.png
2025-02-09 08:26:00,306 ERROR The joined path (C:\Users\ivano\simple-votings-py-charmers\main\media\avatars\default.png) is located outside of the base path component (C:\Users\Мирослав\votings\simple-votings-py-charmers\simple-votings-py-charmers\main\media)
Traceback (most recent call last):
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\ivano\simple-votings-py-charmers\main\media\avatars\default.png) is located outside of the base path component (C:\Users\Мирослав\votings\simple-votings-py-charmers\simple-votings-py-charmers\main\media)
2025-02-09 08:26:00,321 WARNING Bad Request: /media/C:/Users/ivano/simple-votings-py-charmers/main/media/avatars/default.png
2025-03-26 01:45:57,652 ERROR The joined path (C:\Users\ivano\simple-votings-py-charmers\main\media\avatars\default.png) is located outside of the base path component (C:\Users\Мирослав\votings\simple-votings-py-charmers\simple-votings-py-charmers\main\media)
Traceback (most recent call last):
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\ivano\simple-votings-py-charmers\main\media\avatars\default.png) is located outside of the base path component (C:\Users\Мирослав\votings\simple-votings-py-charmers\simple-votings-py-charmers\main\media)
2025-03-26 01:45:57,776 WARNING Bad Request: /media/C:/Users/ivano/simple-votings-py-charmers/main/media/avatars/default.png
2025-03-26 05:39:25,932 INFO New user registered: Иннокентий
2025-03-26 05:39:25,976 ERROR The joined path (C:\Users\ivano\simple-votings-py-charmers\main\media\avatars\default.png) is located outside of the base path component (C:\Users\Мирослав\votings\simple-votings-py-charmers\simple-votings-py-charmers\main\media)
Traceback (most recent call last):
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\ivano\simple-votings-py-charmers\main\media\avatars\default.png) is located outside of the base path component (C:\Users\Мирослав\votings\simple-votings-py-charmers\simple-votings-py-charmers\main\media)
2025-03-26 05:39:25,994 WARNING Bad Request: /media/C:/Users/ivano/simple-votings-py-charmers/main/media/avatars/default.png
2025-03-26 05:39:30,105 ERROR The joined path (C:\Users\ivano\simple-votings-py-charmers\main\media\avatars\default.png) is located outside of the base path component (C:\Users\Мирослав\votings\simple-votings-py-charmers\simple-votings-py-charmers\main\media)
Traceback (most recent call last):
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\ivano\simple-votings-py-charmers\main\media\avatars\default.png) is located outside of the base path component (C:\Users\Мирослав\votings\simple-votings-py-charmers\simple-votings-py-charmers\main\media)
2025-03-26 05:39:30,120 WARNING Bad Request: /media/C:/Users/ivano/simple-votings-py-charmers/main/media/avatars/default.png
2025-03-26 05:39:37,915 ERROR The joined path (C:\Users\ivano\simple-votings-py-charmers\main\media\avatars\default.png) is located outside of the base path component (C:\Users\Мирослав\votings\simple-votings-py-charmers\simple-votings-py-charmers\main\media)
Traceback (most recent call last):
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\Мирослав\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\ivano\simple-votings-py-charmers\main\media\avatars\default.png) is located outside of the base path component (C:\Users\Мирослав\votings\simple-votings-py-charmers\simple-votings-py-charmers\main\media)
2025-03-26 05:39:37,934 WARNING Bad Request: /media/C:/Users/ivano/simple-votings-py-charmers/main/media/avatars/default.png
